app:
  profile: local
  port: 8080
  configserver:
    gituri: https://github.com/jghamburg/lsb2-config-data.git
    cloneOnStart: true
    skipSslValidation: true

image:
  tag: local

fullnameOverride: "lsb2-config-server"

service:
  name: lsb2-config-service
  description: The netflix config service
  type: ClusterIP
  port: 80
  targetPort: 8080
