server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.scm.otto.de/scm/pport/lsb2-config-data.git

# tag::secured[]
security:
  user:
    password: password
# tag::secured[]
