server:
  port: 8888
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always # never always
  health:
    defaults:
      enabled: true
#
#
info:
  app:
    name: Spring Cloud Config Server
    description: This service provides Configuration Management for other microservices
#
# 
spring:
  application: lsb2-config-server
  config:
    use-legacy-processing: true  
  cloud:
    config:
      server:
        git:
          # uri: ${CONFIG_SERVER_GIT_URI:https://github.com/jghamburg/lsb2-config-data.git}
          uri: ${CONFIG_SERVER_GIT_URI:${HOME}/git/learning-spring/lsb2/lsb2-config-data}
          clone-on-start: ${CONFIG_SERVER_CLONE_ON_START:true}
          skip-ssl-validation: ${CONFIG_SERVER_SKIP_SSL_VALIDATION:true}
#          force-pull: true
#          deleteUntrackedBranches: true
#          timeout: 5 # secs
# tag::secured[]
security:
  user:
    password: password
# tag::secured[]