server:
  port: 8888
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
#
# 
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URI:-file:///Users/jgellien/git/PPORT/lsb2/lsb2-config-data}
          clone-on-start: false
#          uri: https://bitbucket.scm.otto.de/scm/pport/lsb2-config-data.git
#          skipSslValidation: true
#          timeout: 5 # secs
# tag::secured[]
security:
  user:
    password: password
# tag::secured[]
