server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URI:-file:///Users/jgellien/git/PPORT/lsb2-config-data}
          clone-on-start: false
#          uri: https://bitbucket.scm.otto.de/scm/pport/lsb2-config-data.git
#          skipSslValidation: true
#          timeout: 5 # secs
# tag::secured[]
security:
  user:
    password: password
# tag::secured[]
