# environment variables for any dev environment
version: '3.1'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-config-server:
    labels:
      lsb2.template.description: "Configuration Server for local environment"
      lsb2.version: "local"
    image: "config-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-config-server.jar
    ports:
      - "8888:8888" # web port
    environment:
      PROFILE: "local"
      CONFIG_SERVER_GIT_URI: "/gitrepo"
    volumes:
      - ${HOME}/git/lsb2/lsb2-config-data:/gitrepo
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true
